Repository hackclub/sprig, pull requests merged in 2022-12, with the labels that each got.

#594 Bottom of the Barrel
  games/Bottom_of_the_Barrel.js
Labels: submission

#595 Fish_in_the_Sea
  games/Fish_in_the_Sea.js
Labels: submission

#596 Fish_in_the_Sea-Update
  games/img/Fish_in_the_Sea.png
Labels: update

#598 Icy Portals
  games/Icy Portals.js
Labels: submission

#599 Bottom_of_the_Barrel
  games/Bottom_of_the_Barrel.js
Labels: update

#608 Bottom_of_the_Barrel
  games/Bottom_of_the_Barrel.js
Labels: update

#611 Jet_Box
  games/Jet_Box.js
  games/img/Jet_Box.png
Labels: submission

#612 Fix fish in the sea
  games/Fish_in_the_Sea.js
Labels: update

#607 music-be-like
  games/music-be-like.js
Labels: submission

#618 bbbbbb
  games/bbbbbb.js
  games/img/bbbbbb.png
Labels: submission

#619 Add files via upload
  games/Pac_Man.js
Labels: submission

#616 Stop
  games/Stop.js
  games/The_Pet.js
  games/img/Stop.png
  games/img/The_Pet.png
Labels: submission

#620 Temple
  games/Temple.js
  games/img/Temple.png
Labels: submission

#621 Bottom_of_the_Barrel
  games/Bottom_of_the_Barrel.js
Labels: update

#522 Invisible Maze
  games/Invisible_Maze.js
  games/img/Invisible_Maze.png
Labels: submission

#622 Bugfix and improve text
  games/Flurffy.js
Labels: update

#623 Worldcraft
  games/Worldcraft.js
Labels: submission

#624 Maze Runner
  games/Maze_Runner.js
Labels: submission

#601 Add files via upload
  cricket_frenzy.js
Labels: submission

#625 Add randomworld
  games/img/randomworld.png
  games/randomworld.js
Labels: submission

#600 sprig_dodge.js tutorial
  games/sprig_dodge.js
Labels: enhancement, beginner friendly

#634 Add Cookie Clicker Game
  games/cookie_clicker.js
  games/img/cookie_clicker.png
Labels: submission

#638 Add Lights Out game
  games/lights_out.js
Labels: submission

#639 Add BigButton Game
  games/BigButton.js
  games/img/BigButton.png
Labels: submission

#640 Add new game DVD logo simulator
  games/dvd_logo_simulator.js
  games/img/dvd_logo_simulator.png
  games/metadata.json
Labels: submission

#641 Update to the Tron we all know and love
  games/Tron.js
Labels: update

#643 Crimbletips
  games/crimbletips.js
  games/img/crimbletips.png
Labels: submission

#642 Mirror Mirror
  games/Mirror_Mirror.js
Labels: submission

#628 13 medium sokoban puzzles
  games/13 medium sokoban puzzles.js
Labels: submission

#647 Box Jump
  games/Box_Jump.js
Labels: submission

#649 Robot Party
  games/Robot_Party_Basic_Buildv1.js
  games/img/Robot_Party_Basic_Buildv1.jpg
Labels: submission

#657 Terminal-Dungeon
  games/Terminal-Dungeon.js
  games/img/terminal-dungeon.png
Labels: submission

#658 Update!
  games/Robot_Party_Basic_Buildv1.js
Labels: update

#660 Update Fish_in_the_Sea.js
  games/Fish_in_the_Sea.js
Labels: update

#655 Lava the Impossible maze Sprig submission
  games/Lava_the_impossible_maze.js
Labels: submission

#661 Add black_jack.js
  games/black_jack.js
  games/img/black_jack.png
Labels: submission

#654 Add Hack Craft
  games/hackcraft.js
  games/img/hackcraft.png
Labels: submission

#659 gravity_fun
  games/gravity_fun.js
  games/img/gravity_fun.png
Labels: submission

#665 fix security bug (#496)
  dispatches/init.js
Labels: enhancement

#663 Update black_jack formatting and little exploit
  games/black_jack.js
Labels: update

#671 charge
  games/charge.js
  games/img/charge.png
Labels: submission

#672 Get_the_birdie
  get_the_birdie.js
Labels: submission

#673 SprigAdventure
  games/sprigadventure.js
Labels: submission

#664 shitpest:3
  games/shitpest.js
Labels: submission

#675 Sort
  games/Sort.js
  games/img/Sort.png
Labels: submission

#677 Colour Game
  games/Colour_Game.js
Labels: submission

#678 Cross_the_Road game added
  games/Cross_The_Road.js
  games/img/Cross_The_Road.png
Labels: submission

#679 Add Guidance.js
  games/guidance.js
Labels: submission

#680 Dragon Fest
  games/Dragon_Fest.js
  games/img/Dragon_Fest.png
Labels: submission

#681 duplicate maze_runner fix
  games/maze_runner.js
  games/maze_runner2.js
Labels: update

#682 Add specifications for screw length in steps
  docs/ASSEMBLY.md
Labels: documentation

#684 Friendly Figures
  games/Friendly_Figures.js
  games/img/Friendly_Figures.png
Labels: submission

#683 Burger_Maker_V1
  games/Burger_Maker_V1.js
  games/img/Burger_Maker_V1.png
Labels: submission

#685 A_Really_One_Sided_Duel
  games/A_Really_One_Sided_Duel.js
  games/img/A_Really_One_Sided_Duel.png
Labels: submission

#686 Added restart in Cross_the_Road.js
  games/Cross_The_Road.js
Labels: update

#690 offline_t-rex_game
  games/img/offline_t-rex_game.png
  games/offline_t-rex_game.js
  games/offline_t-rex_game.png
Labels: submission

#694 Asteroid_Apocalypse
  games/Asteroid_Apocalypse.js
  games/img/Asteroid_Apocalypse.png
Labels: submission
