Repository hackclub/sprig, pull requests merged in 2022-11, with the labels that each got.

#480 Add files via upload
  escape_room.js
Labels: submission

#495 QuadraPedal
  games/QuadraPedal.js
  games/img/QuadraPedal.png
Labels: submission

#492 Add Bert Blaster Game
  games/bertblaster.js
Labels: submission

#500 PushBattle
  games/PushBattle.js
Labels: submission

#502 Brick Dodger by LF
  games/BRICK DODGER.js
  games/img/thumbnail.png
Labels: submission

#503 i made a few games
  games/Art.js
  games/Builder.js
  games/Monty_Hall.js
  games/metadata.json
Labels: submission

#505 Apple Skedaddle
  games/Apple Skedaddle.js
  games/img/Thumbnail Apple.png
Labels: submission

#506 inconsequential leveldungeon
  games/img/inconsequential_leveldungeon.png
  games/inconsequential_leveldungeon.js
Labels: submission

#507 dihydrogen_monoxide_free_fall
  games/dihydrogen_monoxide_free_fall.js
  games/img/dihyrdogen_monoxide_free_fall.png
Labels: submission

#511 woo screen scroll
  games/coding_demo_4_screen_scroll.js
  games/metadata.json
Labels: submission

#504 L0st (Game for sprig)
  games/L0st.js
  games/img/L0st.png
Labels: submission

#514 Add Conways Game of Life
  games/conwaysgameoflife.js
  games/img/conwaysgameoflife.png
  games/metadata.json
Labels: submission

#515 Add Amoeba game
  games/Amoeba.js
  games/img/Amoeba.png
Labels: submission

#517 Racer
  games/img/racer.png
  games/racer.js
Labels: submission

#524 Snake
  games/Snake.js
  games/img/Snake.png
Labels: submission

#475 PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#525 Push the Blocks
  games/push_ the_blocks.js
Labels: submission

#530 Speedy Snake Game
  games/img/speedy_snake.png
  games/speedy_snake.js
Labels: submission

#531 EverHot
  games/ever_hot.js
  games/img/Everhot.png
Labels: submission

#534 virus_plowing
  games/img/virus_plowing.png
  games/virus_plowing.js
Labels: submission

#533 Dual State Machine
  games/dual_state_machine.js
  games/img/dual_state_machine.png
  games/metadata.json
Labels: submission

#518 Cave Explorer
  games/cave_explorer.js
Labels: submission

#536 Dogs vs Cats
  games/DogsvsCats.js
  games/img/DogsvsCats.png
Labels: submission

#542 woo gravity
  games/coding_demo_5_gravity.js
  games/metadata.json
Labels: submission

#546 Add files via upload
  games/cool_platformer.js
Labels: submission

#548 UFO Attack
  games/UFO_Attack.js
  games/img/UFO_Attack.png
Labels: submission

#549 The IMPOSSIBLE Puzzle
  games/the_impossible_puzzle.js
Labels: submission

#554 Add Soko Quest to the game library
  games/img/soko_quest.PNG
  games/soko_quest.js
Labels: submission

#550 echolocation
  games/echolocation.js
  games/img/echolocation.png
  games/metadata.json
Labels: submission

#556 Jumper
  games/Jumper.js
  games/img/Jumper.png
Labels: submission

#557 Add another version of Simon
  games/Simon-WASD_Edition.js
Labels: submission

#560 the_invisible_man
  games/the_invisible_man.js
Labels: submission

#562 Mastermind
  games/Mastermind.js
  games/img/Mastermind.png
  games/metadata.json
Labels: submission

#532 Create spriggymon.js
  games/spriggymon.js
Labels: submission

#565 Added my game Delightful Mazes
  games/delightful_mazes.js
Labels: submission

#570 New Game - Chuckman Go!
  games/chuckman_go.js
Labels: submission

#569 Snake_4_2
  games/Snake_4_2.js
  games/img/Snake_4_2.png
Labels: submission

#574 Sprigle
  games/img/sprigle.png
  games/sprigle.js
Labels: submission

#575 change 'of' to 'off' in ASSEMBLY.md
  docs/ASSEMBLY.md
Labels: documentation

#577 Update virus_plowing.js
  games/virus_plowing.js
Labels: update

#578 Update virus_plowing.js
  games/virus_plowing.js
Labels: update

#568 Add Support for Firefox 91
  index.css
Labels: enhancement

#580 the RUN
  games/img/the RUN.png
  games/the_RUN.js
Labels: submission

#494 Added a beginner workshop to the docs page
  docs/BEGINNER_WORKSHOP.md
  docs/assets/default-window.png
  docs/assets/map-editor.png
  docs/assets/sprite-editor.png
Labels: documentation

#540 Add Github workflow to test PRs
  .github/workflows/test-game.yml
  tests/sprigfuzzy_workflow.js
Labels: enhancement

#571 Meteor shower
  games/Meteor_shower.js
Labels: submission

#582 solar_system
  games/solar_system.js
Labels: submission

#583 Galacticats
  games/Galacticats.js
  games/img/galacticats.png
Labels: submission

#579 restocking simulater
  games/restocker simulater sprig.js
Labels: submission

#523 BoxCubeGuy
  games/BoxCubeGuy.js
  games/img/BlockCubeGUyThumbnail.png
  games/img/BoxCubeGuy.png
Labels: submission

#529 Asteroid Field
  games/Asteroid_Field.js
Labels: submission

#586 creepy_crush
  games/creepy_crush.js
  games/img/creepy_crush.png
Labels: submission

#587 LOADSAMONEY
  games/loadsamoney.js
Labels: submission

#584 Fix the audio on lovelock
  games/love_lock.js
Labels: update
