Repository hackclub/sprig, pull requests merged in 2023-10, with the labels that each got.

#1157 Space War
  games/Space war.js
Labels: submission

#1161 Find the Watermelon submission
  games/find_the_watermelon.js
Labels: submission

#1165 spider_home
  games/img/spider_home.PNG
  games/spider_home.js
Labels: submission

#1164 added game
  games/Destroy_The_Hearts.js
Labels: submission

#1160 Sprikipedia, The Sprig wiki and encyclopedia - Translation to Portuguese (WIP)
  public/translations/EN.json
  public/translations/PT.json
Labels: enhancement, sprikipedia

#1056 ocean maze escape
  games/ocean-maze-escape.js
Labels: submission

#1170 Learn Morse
  games/learn_morse.js
Labels: submission

#1171 The Legend Of Sprig
  games/The_Legend_Of_Sprig.js
  games/img/The_Legend_Of_Sprig.png
Labels: submission

#1172 Swapper
  games/Swapper.js
  games/img/Swapper.png
Labels: submission

#1180 fixing my thumb issue
  games/img/learn_morse.png.PNG
Labels: update

#1168 gravity_box
  games/gravity_box.js
Labels: submission

#1178 for_Squiggly_myLost_worm.js
  games/for_Squiggly_myLost_worm.js
Labels: submission

#1188 Bastion Content Update
  games/bastion.js
Labels: update

#1189 GAME UPDATE!!
  games/learn_morse.js
Labels: update

#1187 Boxxod.js
  games/Boxxod.js
Labels: submission

#1103 Mario_Platformer_updated
  games/Mario_Platformer_v2.js
Labels: submission

#1191 fixing game thumb name issue
  games/img/learn_morse.png
  games/img/learn_morse.png.PNG
Labels: update

#1190 Added Zap game
  games/img/zap.png
  games/zap.js
Labels: submission

#1197 make shooter game
  games/shooter.js
Labels: submission

#1198 turtle game (reach the beach)
  games/img/turtle game (reach the beach).png
  games/turtle_game_(reach_the_beach).js
Labels: submission

#1199 adding in a picture for my already sumbitted game
  games/img/turtle game (reach the beach).png
  games/img/turtle_game_(reach_the_beach).png
Labels: update

#1203 feat: add my game "galactic coconuts"
  games/galactic_coconuts.js
Labels: submission

#1201 Custom_Tic_Tac_Toe
  games/Custom_Tic_Tac_Toe.js
  games/img/Custom_Tic_Tac_Toe.png
Labels: submission
