Repository hackclub/sprig, pull requests merged in 2023-08, with the labels that each got.

#1101 pb & j maze!
  games/breakfast_maze!.js
  games/img/breakfast_maze!.png
  games/img/pb&j maze!.png
  games/img/pb_&_j_maze!.png
Labels: submission

#1100 Thunder Bowl
  games/img/hackclub- thunder bowl.png
  games/thunder_bowl.js
  games/thunderball.png
Labels: submission

#1081 feature: tutorial panel for Sprig tutorials
  src/components/big-interactive-pages/editor.tsx
  src/components/popups-etc/help.module.css
  src/components/popups-etc/help.tsx
  src/components/popups-etc/tutorial-warning.module.css
  src/components/popups-etc/tutorial-warning.tsx
  src/lib/game-saving/account.ts
  src/lib/game-saving/auth-helper.ts
  src/lib/state.ts
  src/pages/api/games/new.ts
  src/pages/api/games/save.ts
  src/pages/gallery/[filename].astro
  src/pages/~/[id].astro
Labels: enhancement

#1083 Improve getting_started tutorial
  games/getting_started.js
  games/getting_started.md
Labels: content, blocked

#1114 4_Colour_Drawing
  games/4_Colour_Drawing.js
  games/img/4_Colour_Drawing.png
Labels: submission

#1112 Add `Dynamic_Adventure.js`
  games/Dynamic_Adventure.js
  games/img/Dynamic_Adventure.png
Labels: submission

#1116 Burger Build
  burger-build.js
Labels: submission

#1113 Sprigressbar
  games/Sprigressbar.js
  games/img/Sprigressbar.png
Labels: submission

#1118 Add Battleship.js
  games/Battleship.js
Labels: submission

#1121 The Legend of Zelda: Link's Escape
  games/The_Legend_of_Zelda-Links_Escape
Labels: submission

#1123 Eat & Don't Be Eaten
  games/Eat_&_Don't_Be_Eaten.js
Labels: submission

#1124 Move burger_build.js to games directory
  games/burger_build.js
Labels: update
