Repository hackclub/sprig, pull requests merged in 2023-01, with the labels that each got.

#695 Robot Party Bug Fixes
  games/Robot_Party_Basic_Buildv1.js
Labels: update

#696 Add pong-multiplayer game
  games/pong-multiplayer.js
Labels: submission

#697 Create missile_mania.js
  games/missile_mania.js
Labels: submission

#700 Add files via upload
  games/Number_Nudger.js
Labels: submission

#653 Add files via upload
  games/Protect The Surfer.js
Labels: submission

#704 feature: Add font explorer tool.
  games/font-explorer.js
  games/img/font-explorer.png
Labels: submission

#666 Fix some grammar mistakes in GROWING_A_SPRIG.md
  docs/GROWING_A_SPRIG.md
Labels: documentation

#705 Amongus Flight
  games/Amongus flight.js
Labels: submission

#706 Update The_Pet.js
  games/The_Pet.js
Labels: update

#703 Avoid the Tree
  games/Avoid_The_Tree.js
  games/img/Avoid_The_Tree.png
Labels: submission

#707 SprigClick
  games/SprigClick.js
  games/img/SprigClick.png
Labels: submission

#709 Cube Escape
  games/cube_escape.js
Labels: submission

#702 5-in-1 Carnival Game Pack
  games/5-in-1-Carnival-Game-Pack!.js
Labels: submission

#708 Add files via upload
  games/CATCH-ME.js
  games/img/CATCH-ME.png
Labels: submission

#710 aMAZE game
  games/aMAZE.js
Labels: submission

#712 The Bird Feedo
  games/The_Bird_Feedo.js
Labels: submission

#714 Recreation of Battle City in Sprig
  games/Battle_City.js
  games/img/Battle_City.png
Labels: submission

#715 Fractal generator sprig app
  games/fractal_generator.js
  games/img/fractal_generator.png
Labels: submission

#717 Let_Them_Eat_Cake
  games/Let_Them_Eat_Cake.js
  games/img/Let_Them_Eat_Cake.png
Labels: submission

#719 Fix the locked in a box bug for the hot-diggity-dog game
  games/hot-digitty-dog.js
Labels: update

#724 Add a Keytester
  games/keyTester.js
Labels: submission

#727 Bullet Dodge
  games/bullet-dodge.js
  games/img/bullet_dodge.png
Labels: submission

#720 Added ElfSokoban
  games/ElfSokoban.js
Labels: submission

#728 Mario_Kart
  games/Mario_Kart.js
  games/img/sprig_mario.png
Labels: submission

#729 Add files via upload
  games/brick_breaker.js
Labels: submission

#731 Uploaded scrolling maze
  games/scrolling_maze.js
Labels: submission

#733 It_Is_Coming_Out!
  games/It_Is_Coming_Out!.js
  games/img/Can't_Hold_It_In!.png
Labels: submission

#732 Added new game: 1930!
  games/1930.js
  games/img/1930.png
Labels: submission

#740 Alien Attack game submission
  games/Alien_Attack.js
  games/img/Alien_Attack.png
Labels: submission

#738 Cricket Dodge
  games/Cricket-Dodge.js
  games/img/Cricket-Dodge.png
Labels: submission

#721 Constrain BPM input in the Sequencer.
  sequencer/sequencer.js
Labels: enhancement

#627 Add files via upload
  games/Tic-Tac-Toe.js
Labels: submission

#742 Christmas Themed Sokoban
  games/Christmas_Themed_Sokoban.js
Labels: submission

#739 PR Template update
  .github/PULL_REQUEST_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#744 The UFO Farm
  games/The_UFO_farm.js
Labels: submission

#745 Sequencer now plays selected note
  sequencer/sequencer.js
Labels: enhancement

#747 Added new Sprig game
  games/explorer.js
Labels: submission

#748 Various bugfixes and optimizations to bullet_dodge.js
  games/bullet_dodge.js
Labels: update

#749 feat: Added Slow Motion for cube_escape.js
  games/cube_escape.js
Labels: update

#735 Astrovoid
  games/Astrovoid.js
  games/img/Astrovoid.png
Labels: submission

#751 Added restart, removed fatal bug which spawned infinite infinite loops - Bullet Dodge
  games/bullet_dodge.js
Labels: update

#754 Add Hex Hubbub
  games/hex_hubbub.js
  games/img/hex_hubbub.png
Labels: submission

#755 Add `squarey_runs_away_from_the_fireball`
  games/squarey_runs_away_from_the_fireball.js
Labels: submission

#756 Add SpriggyMorse
  games/spriggy_morse.js
Labels: submission

#760 son_of_a_lich
  games/img/son_of_a_lich.png
  games/son_of_a_lich.js
Labels: submission

#761 Fire_Hound
  games/Fire_Hound.js
  games/img/Fire_Hound.png
Labels: submission

#759 Super Efficient Bunny by Mihir S.
  games/Super_Efficient_Bunny.js
Labels: submission
