Repository hackclub/sprig, pull requests merged in 2023-05, with the labels that each got.

#1009 Add files via upload
  games/FRC_TEAM_2016_Monkey_Madness.js
Labels: submission

#1012 Antivirus
  games/Antivirus.js
Labels: submission

#1019 Add portal game
  games/img/portal_game.png
  games/portal_game.js
Labels: submission

#1017 Added Hangman
  games/hangman.js
Labels: submission

#1018 Add Game "Hidden Maze"
  games/hidden_maze.js
Labels: submission

#1022 Pet the Cat
  games/Pet_the_Cat.js
Labels: submission

#1025 Add more error messages
  src/lib/engine/1-base/index.ts
  src/lib/engine/2-web/index.ts
  src/lib/upload.ts
Labels: enhancement

#1026 Add Hidden Maze Infinite
  games/hidden_maze_infinite.js
Labels: submission

#1029 Add Frog at the Fungi Maze game!
  games/frog_at_the_fungi_maze.js
  games/img/frog_at_the_fungi_maze.png
Labels: submission

#1027 New game upload for a Personal Sprig Kit.
  games/drab_bullets.js
  games/img/drab_bullets.png
Labels: submission

#1030 Throw console error if glyph doesn't exist.
  src/lib/engine/1-base/text.ts
Labels: enhancement

#1032 A Spike Avoider Game
  games/Spike_Avoider.js
Labels: submission

#1034 Add Maths Speedrun Game
  games/Maths_Speedrun.js
Labels: submission

#1037 Update hidden_maze & hidden_maze_infinite
  games/hidden_maze.js
  games/hidden_maze_infinite.js
Labels: update

#1039 Recycling_Turtle
  games/Recycling_Turtle.js
  games/img/Recycling_Turtle.png
Labels: submission

#1043 add galloping game to repo :D
  games/galloping.js
Labels: submission

#1044 Add Game: Hidden Maze Escape
  games/hidden_maze_escape.js
Labels: submission

#1045 Operation_Ocean
  games/Operation_Ocean.js
Labels: submission

#1049 Mirror_Snake
  games/Mirror_Snake.js
  games/img/Mirror_Snake.png
Labels: submission

#1052 DontGetBurnt
  games/DontGetBurnt.js
  games/img/DontGetBurnt.png
Labels: submission

#1053 The Story of Grass
  games/The_Story_of_Grass.js
Labels: submission

#1054 Update GET_A_SPRIG.md
  docs/GET_A_SPRIG.md
Labels: content
