Repository hackclub/sprig, pull requests merged in 2023-03, with the labels that each got.

#879 whack_a_mole
  games/img/whack_a_mole.png
  games/whack_a_mole.js
Labels: submission

#887 Labyrinth3
  games/Labyrinth3.js
Labels: submission

#888 Add bobs bad apple to games folder.
  games/bobs_bad_apple.js
Labels: submission

#893 calculator
  games/calculator.js
  games/img/calculator.png
Labels: submission

#868 Add files via upload
  games/Memory_Test.js
Labels: submission

#907 Disco
  games/Disco.js
  games/img/Disco.png
Labels: submission

#906 Update rescue_leo.js
  games/rescue_leo.js
Labels: update

#942 Dodge The Rock
  games/Dodge_The_Rock.js
Labels: submission

#944 Add Binary Eater Game
  games/Binary_Eater.js
Labels: submission

#946 Added MusicalTiles via upload
  games/MusicalTiles.js
Labels: submission

#941 add me game (fight big parma)
  games/fight_big_parma.js
  games/img/fight_big_parma.png
Labels: submission

#956 girl_scouts_x_hack_club
  games/girl_scouts_x_hack_club.js
Labels: submission

#961 Added CatchIt
  games/CatchIt.js
Labels: submission

#966 fill_the_map.js
  games/fill_the_map.js
Labels: submission

#962 Added MagicalTiles by Shreeya Rani
  games/MagicalTiles.js
Labels: submission

#851 Capitalise "Games" / "Game"
  src/components/navbar-editor.tsx
Labels: enhancement

#969 Maze_Runner3
  games/Maze_Runner3.js
Labels: submission

#979 TwinPrimeRockets Game
  games/TwinPrimeRockets.js
Labels: submission

#987 Add duck hunt game
  games/Duck_Hunt.js
  games/img/Duck_Hunt.png
Labels: submission

#986 Rickroll
  games/img/rickroll.png
  games/rickroll.js
Labels: submission

#991 Physics Sandbox
  games/Physics_Sandbox.js
  games/img/Physics_Sandbox.png
Labels: submission

#954 Highlight erroring line
  src/components/big-interactive-pages/editor.tsx
  src/global.css
  src/lib/engine/3-editor/error.ts
  src/lib/state.ts
Labels: bug
