Repository hackclub/sprig, pull requests merged in 2023-02, with the labels that each got.

#767 🎮 TicTacToe - Remake of Atharv's version
  games/Tic Tac Toe.js
Labels: submission

#769 Add `Find the suspect` game 👮‍♂️
  games/Find_The_Suspect.js
  games/img/Find_The_Suspect.png
Labels: submission

#757 Tic-Tac-No
  games/Tic-Tac-No.js
  games/img/Tic-Tac-No.png
Labels: submission

#770 Rolling Obstacles
  games/Rolling_Obstacles.js
  games/img/Rolling Obstacles.png
Labels: submission

#772 Fixed a minor bug (`Find the Suspect`)
  games/Find_The_Suspect.js
Labels: update

#775 Falling Water 2.0 Update
  games/Falling_Water.js
Labels: update

#780 Falling Water bugfix, and a new thumbnail.
  games/Falling_Water.js
  games/img/Falling_Water.png
Labels: update

#782 Update Snek.js
  games/snek.js
Labels: update

#779 pusher game
  games/pusher_game.js
Labels: submission

#741 Improve Tetris music (Korobeiniki) and improve button mapping
  games/tetris.js
Labels: update

#783 Add files via upload
  games/Sus_Runner.js
Labels: submission

#786 Sprig Shoot
  games/sprig_shoot.js
Labels: submission

#785 The Sky Is Falling For Real This Time
  games/The_Sky_Is_Falling_For_Real_This_Time.js
Labels: submission

#790 3D_wire_frame_rendererV1
  games/3D_wire_frame_rendererV1.js
  games/img/3D_wire_frame_rendererV1.png
Labels: submission

#787 Labyrinth
  games/Labyrinth.js
Labels: submission

#792 Create ValentinesGame.js
  games/ValentinesGame.js
Labels: submission

#791 The Maze of Sprig
  games/The_Maze_of_Sprig.js
  games/img/TheMazeOfSprig.png
Labels: submission

#794 Labyrinth2
  games/Labyrinth2.js
Labels: submission

#796 Plants vs. Zombies
  games/plants_vs_zombies.js
Labels: submission

#805 Cave Quest
  games/Cave-Quest.js
Labels: submission

#807 tunnel
  games/tunnel.js
Labels: submission

#808 Dino
  games/dino.js
Labels: submission

#809 microwars
  games/microwars.js
Labels: submission

#813 Add wet-sand.js game
  games/img/wet-sand.png
  games/wet-sand.js
Labels: submission

#814 RandomDungeon
  games/RandomDungeon-final.js
  games/img/RandomDungeon-final.png
Labels: submission

#812 Bloxorz
  games/bloxorz.js
Labels: submission

#821 Flamin_Fingers
  games/Flamin_Finger.js
  games/img/Flamin_Finger.png
Labels: submission

#849 i added the something
  docs/ASSEMBLY.md
Labels: documentation

#831 Street Racer game
  games/Street_Racer.js
Labels: submission

#854 Update randomworld
  games/img/randomworld.png
  games/randomworld.js
Labels: update

#850 connectTheDots
  games/connectTheDots.js
  games/img/connectTheDots.png
Labels: submission

#852 Update spirg assembly docs
  docs/ASSEMBLY.md
Labels: documentation

#866 Include unnamed games in game count
  src/pages/~/index.astro
Labels: enhancement, Sprig 2.0

#859 the_dining_room_in_the_sky
  games/the_dining_room_in_the_sky.js
Labels: submission

#858 Fix sprig button mapping
  public/sprig.glb
Labels: enhancement, Sprig 2.0
