Repository hackclub/sprig, pull requests merged in 2023-09, with the labels that each got.

#1125 Spirit Bound
  games/img/spirit-bound.png
  games/spirit-bound.js
Labels: submission

#1128 The Legend of Zelda: Link's Escape - Update
  games/The_Legend_of_Zelda-Links_Escape
Labels: update

#1129 Sprikipedia, The Sprig wiki and encyclopedia - Under development (2)
  public/translations/EN.json
  public/translations/PT.json
  src/components/spriki-components/Dark.astro
  src/components/spriki-components/Docs.astro
  src/components/spriki-components/Lang.astro
  src/components/spriki-components/Navspriki.astro
  src/layouts/categories.astro
  src/layouts/docs.astro
  src/pages/sprikipedia/about/index.astro
  src/pages/sprikipedia/brand/index.astro
  src/pages/sprikipedia/firmware/index.astro
  src/pages/sprikipedia/getting-started/index.astro
  src/pages/sprikipedia/global.css
  src/pages/sprikipedia/hardware/index.astro
  src/pages/sprikipedia/index.astro
  src/pages/sprikipedia/team/index.astro
  src/pages/sprikipedia/translations/translations.json
  src/pages/sprikipedia/tutorials/github/edit-a-comment.md
  src/pages/sprikipedia/tutorials/github/make-a-comment.md
  src/pages/sprikipedia/tutorials/github/make-a-pr.md
  src/pages/sprikipedia/tutorials/github/update-a-pr.md
  src/pages/sprikipedia/tutorials/index.astro
Labels: enhancement

#1130 FOOD-CATCH
  games/FOOD-CATCH.js
  games/img/FOOD-CATCH.PNG
  games/img/FOOT CATCH.PNG
  games/img/FOOT-CATCH.PNG
Labels: submission

#1132 Add files via upload
  games/mailman.js
Labels: submission

#1120 TICTACGPT
  games/Tic_Tac_GPT.js
Labels: submission

#1135 pr again
  games/ding_dong-delivery.js
Labels: submission

#1136 Tried to submit Flappy Sprig to
  games/flappysprig.js
Labels: submission

#1137 Two Player Tetris Game
  games/Two_Player_Tetris.js
  games/img/Two_Player_Tetris.png
Labels: submission

#1141 Added game killer_training
  games/killer_training.js
Labels: submission

#1143 fixed issue where my game wouldn't open on gallery
  games/killer_training.js
  games/metadata.json
Labels: update

#1140 Wham Game Submission
  games/wham.js
Labels: submission

#1131 Sprikipedia, The Sprig wiki and encyclopedia - Under development (3)
  .astro/types.d.ts
  .gitpod.yml
  public/translations/EN.json
  public/translations/PT.json
  src/layouts/categories.astro
  src/layouts/docs.astro
  src/pages/sprikipedia/about/index.astro
  src/pages/sprikipedia/firmware/index.astro
  src/pages/sprikipedia/global.css
  src/pages/sprikipedia/hardware/index.astro
  src/pages/sprikipedia/index.astro
  src/pages/sprikipedia/team/index.astro
  src/pages/sprikipedia/translations/translations.json
  src/pages/sprikipedia/tutorials/github/edit-a-comment.astro
  src/pages/sprikipedia/tutorials/github/edit-a-comment.md
  src/pages/sprikipedia/tutorials/github/make-a-comment.astro
  src/pages/sprikipedia/tutorials/github/make-a-comment.md
  src/pages/sprikipedia/tutorials/github/make-a-pr.astro
  src/pages/sprikipedia/tutorials/github/make-a-pr.md
  src/pages/sprikipedia/tutorials/github/update-a-pr.astro
  src/pages/sprikipedia/tutorials/github/update-a-pr.md
  src/pages/sprikipedia/tutorials/index.astro
  src/translations/en_US.json
  src/translations/pt_BR.json
Labels: enhancement

#1089 fire boom
  games/fire_boom.js
Labels: submission

#1154 Updated game killer_training
  games/killer_training.js
Labels: update
