Repository hackclub/sprig, pull requests merged in 2023-12, with the labels that each got.

#1286 compudino
  games/compudino.js
Labels: submission

#1290 Bob And Joe
  games/bob_and_joe.js
Labels: submission

#1291 bomb dodge
  games/bomb_dodge.js
Labels: submission

#1276 update /team
  src/pages/sprikipedia/team/index.astro
  src/translations/en_US.json
  src/translations/pt_BR.json
Labels: sprikipedia

#1226 Integrate help pane into output area under game screen
  src/components/big-interactive-pages/editor.module.css
  src/components/big-interactive-pages/editor.tsx
  src/components/popups-etc/help.module.css
  src/components/popups-etc/help.tsx
Labels: enhancement

#1278 Add files via upload
  games/StickRunner.js
Labels: submission

#1302 added an extra level
  games/fill_the_map.js
Labels: update

#1285 Implemented Automate Plagiarism / Copy Detection
  .github/scripts/extract_percentages.py
  .github/scripts/plagiarism_check.py
  .github/workflows/check_plagiarism.yml
Labels: enhancement

#1313 DoNotConsumeEmptyBowls
  games/DoNotConsumeEmptyBowls.js
  games/img/Do Not Consume Empty Bowls (1).png
  games/img/DoNotConsumeEmptyBowls.png
Labels: submission

#1301 Adding Hungry Ninja Game
  games/Hungry-Ninja.js
Labels: submission

#1174 Hard-Hat Helper
  games/Hard-Hat_Helper.js
Labels: submission

#1307 International morse code trainer
  games/Morse_trainer.js
  games/img/Morse_trainer.png
Labels: submission

#1318 Starjump
  games/starjump.js
Labels: submission

#1304 New Game
  games/move_the_rocks.js
Labels: submission

#1303 Street Fighter
  games/Sprig_Fighter.js
Labels: submission

#1321 Catch the star
  games/Catch_the_star.js
  games/img/Catch_the_star.png
  games/metadata.json
Labels: submission

#1335 maze-eye
  games/img/maze-eye.png
  games/maze-eye.js
Labels: submission

#1340 Rythym
  games/Rythym.js
  games/img/Rythym.png
Labels: submission

#1344 Random Maze Game using DFS Algorithm
  games/img/random_maze_game_with_dfs_algorithm.png
  games/random_maze_game_with_dfs_algorithm.js
Labels: submission

#1341 huff_ptegwu
  games/huff_ptegwu.js
Labels: submission

#1351 taikoMania
  games/img/taikoMania.png
  games/taikoMania.js
Labels: submission

#1350 Nickels
  games/Nickels.js
Labels: submission

#1333 Monkey Catch Food
  games/Monkey_Catch_Food.js
Labels: submission

#1354 Raincatch
  games/Raincatch.js
  games/img/Raincatch.png
Labels: submission
