Repository hackclub/sprig, pull requests merged in 2024-12, with the labels that each got.

#2659 [Sprig App] WCfinal
  games/WCfinal.js
Labels: submission

#2666 [Sprig App] Shapes That Go Portable
  games/Shapes-That-Go-Portable.js
Labels: submission

#2672 [Sprig App] Be_Younique
  games/Be_Younique.js
Labels: submission, approved

#2675 Trapped
  games/Trapped.js
  games/img/Trapped.png
Labels: submission, approved

#2677 Beyblade Battle
  games/beyblade_battle.js
  games/img/beyblade_battle.png
Labels: submission, initial review performed, approved

#2629 [Sprig App] Reach The End Multiplayer
  games/Reach-The-End_Multiplayer.js
Labels: submission, initial review performed, approved

#2673 Catch The Banana
  games/catch-the-banana.js
Labels: submission, initial review performed, approved

#2605 [Sprig App] Sprong
  games/Sprong.js
Labels: submission, initial review performed

#2598 [Sprig App] Saving Blob
  games/Saving-Blob.js
Labels: submission, approved

#2689 RockPaperScissors
  games/RockPaperScissors.js
Labels: submission, approved

#2685 [Sprig App] Hole in Wall
  games/Hole-in-Wall.js
  games/img/Hole-in-Wall.png
Labels: submission, approved

#2683 Cube Castle
  games/CubeCastle.js
  games/img/CubeCastle.png
Labels: submission, approved

#2693 [Sprig App] RockPaperScissors
  games/RockPaperScissors.js
Labels: update, approved

#2700 [Sprig App] ChocolateNimGame
  games/ChocolateNimGame.js
  games/img/ChocolateNimGame.png
Labels: submission, approved

#2701 [Sprig App] Wanna See Me Speedrun?
  games/img/wanna_see_me_speedrun.png
  games/wanna_see_me_speedrun.js
Labels: submission, approved

#2702 The_Hidden_Cheese
  games/The_Hidden_Cheese.js
Labels: submission, approved

#2713 [Sprig App] Cyan
  games/Cyan.js
Labels: submission, approved
