Repository hackclub/sprig, pull requests merged in 2024-01, with the labels that each got.

#1355 osu! mania
  games/img/osu-mania.png
  games/osu-mania.js
Labels: submission

#1353 English Checkers
  games/English_Checkers.js
Labels: submission

#1358 Squilium_Escape
  games/Squilium_Escape.js
Labels: submission

#1300 Blob Runner
  games/Blob_Runner.js
Labels: submission

#1374 Game submission: untitled taiko game
  games/img/taiko_fever.png
  games/taiko_fever.js
Labels: submission

#1379 redirect SPRIGpedia to SPRIKIpedia
  src/pages/sprigpedia.astro
Labels: sprikipedia

#1369 Better code block
  src/components/spriki-components/Code.astro
  src/pages/sprikipedia/getting-started/engine-development.astro
  src/pages/sprikipedia/getting-started/setup.astro
  src/pages/sprikipedia/global.css
Labels: sprikipedia

#1381 fruit_pusher merge - kirby-b
  games/fruit_pusher.js
Labels: submission

#1377 Add files via upload
  games/bone_hunt.js
Labels: submission

#1365 Add files via upload
  games/dicee_dare.js
Labels: submission

#1382 Catch the Apples
  games/Catch-the-apples.js
Labels: submission

#1387 add sprigish
  games/sprigish.js
Labels: submission

#1390 Add files via upload
  games/Fruit_Catcher.js
Labels: submission

#1386 Snowman_Escape
  games/Snowman_Escape.js
Labels: submission

#1403 Find the Clone
  games/find_the_clone.js
Labels: submission

#1147 Add stop button
  src/components/big-interactive-pages/editor.module.css
  src/components/big-interactive-pages/editor.tsx
Labels: enhancement

#1398 CaveGame
  games/CaveGame.js
  games/img/CaveGame.png
Labels: submission

#1407 type_or_die
  games/img/type_or_die.png
  games/type_or_die.js
Labels: submission

#1388 Added MicroBot Adventure
  games/MicroBot_Adventure.js
  games/img/MicroBot_Adventure.png
Labels: submission

#1385 Remove Sprigs Remaining From /get
  src/lib/remaining-consoles.ts
  src/pages/get.astro
  src/pages/index.astro
Labels: content

#1405 Bad Apple port on Sprig
  games/Bad_Apple.js
  games/img/Bad_Apple.png
Labels: submission

#1411 Cup_Game
  games/Cup_Game.js
Labels: submission

#1412 Snake Boxes
  games/Snake_Boxes.js
  games/img/Snake_Boxes.png
Labels: submission
