Repository hackclub/sprig, pull requests merged in 2024-09, with the labels that each got.

#2245 JB's Pushy Blocky Portal Game
  games/JBsPushyBoxPortalGame.js
  games/img/JBsPushyBlockyPortalGame.png
Labels: submission, approved

#2248 Colors Game
  games/ColorsGame.js
  games/img/Screenshot 2024-08-29 140505.png
Labels: submission, approved

#2249 Cheese_Collector
  games/Cheese_Collector.js
Labels: submission, approved

#2244 A Maze
  games/A_Maze.js
Labels: submission

#2250 Falling Tiles
  games/FallingTiles.js
  games/img/FallingTiles.png
Labels: submission, approved

#2253 Project Zero
  games/Project_Zero.js
  games/img/Project_Zero.png
Labels: submission, approved

#2254 Cookie Hacker
  games/CookieHacker.js
  games/img/CookieHacker.png
Labels: submission, approved

#2261 Math Mechanics
  games/Math Mechanics.js
Labels: submission, approved

#2262 Journey of the Yeti
  games/colossal_dewgong(1).js
Labels: submission, approved

#2265 Evil astrokittens
  games/Evil astrokittens.js
Labels: submission, approved

#2266 added JB_Dodge_game.js
  games/JB_Dodge_game.js
Labels: submission, approved

#2267 Add Hue Havoc
  games/Hue_Havoc.js
  games/img/Hue_Havoc.png
Labels: submission, approved

#2274 Add files via upload
  Target Practice-3.js
Labels: submission, approved

#2276 Introduce Word Sculptor
  games/Word_Sculptor.js
Labels: submission, approved

#2277 LabyrinthBoardGame
  games/LabyrinthBoardGame.js
  games/img/LabyrinthBoardGame.png
Labels: submission, approved

#2218 infinite-loop
  games/img/infinite_loop.png
  games/infinite_loop.js
Labels: submission, initial review performed

#2201 Add files via upload
  games/RPS.js
Labels: submission, initial review performed, approved

#2151 Rico Rodriguez (Inspired by JC3)
  games/rico_rodriguez.js
Labels: submission, initial review performed

#2260 Treasure Maze Sprig
  games/Treasure Maze (Correct Version).js
Labels: submission, approved

#2263 JumperWho
  games/eager_rattata.js
Labels: submission, approved

#2264 subway_surfers_infinite_runner
  games/subway surfers.js
Labels: submission, approved

#2234 Maze_Flag_Collector
  games/Maze_Flag_Collector.js
Labels: submission, initial review performed

#2334 Atari classic pong X2 by AVSC
  games/classicpongX2.js
Labels: submission

#2350 Asteroid Beatdown
  games/Asteroid_Beatdown.js
  games/img/Asteroid_Beatdown.png
Labels: submission

#2354 add Hope
  games/Hope.js
Labels: submission

#2351 Add Gauntlet
  games/gauntlet.js
  games/img/gauntlet.png
Labels: submission

#2348 Add files via upload
  games/Pokemon_Game.js
  games/img/Pokemon_Game.png
Labels: submission

#2347 WordeScapes
  games/WordeScapes.js
  games/img/WordeScapes.png
Labels: submission

#2293 SuperFighters Game Code & Level Optimizations
  games/SuperFighters.js
  games/img/SuperFighters.png
Labels: submission, initial review performed

#2130 space-maze
  games/img/space-maze.png
  games/space-maze.js
Labels: submission, initial review performed

#2343 Color Connect
  games/colorconnect.js
  games/img/colorconnect.png
Labels: submission, approved

#2346 Slippy Slidey
  games/Slippy-Slidey.js
Labels: submission, approved

#2357 TheFlood
  games/TheFlood.js
  games/img/TheFlood.png
Labels: submission, approved

#2358 Codekuun
  games/codekuun.js
  games/img/codekuun.png
Labels: submission, approved

#2359 Dont Touch the Cat
  games/Dont Touch the Cat.js
  games/img/Dont Touch the Cat.png
Labels: submission, approved

#2309 Bombs
  games/Bombs.js
  games/img/Bombs.png
Labels: submission, approved

#2298 Turn based game
  games/turnbasedcombatgame.js
Labels: submission, approved

#2120 dungenrun
  games/dungenrun.js
  games/img/dungenrun.png
Labels: submission, initial review performed

#2361 Circuits!
  games/Circuits!.js
  games/img/Circuits!.png
Labels: submission

#2365 Added RickRoll
  games/RickRoll_BW.js
  games/img/RickRoll_BW.png
Labels: submission

#2335 feat(games): banana fuel
  games/Banana fuel.js
Labels: submission, initial review performed

#2337 Eminent's Gateway
  games/gateway.js
Labels: submission, initial review performed
