Repository hackclub/sprig, pull requests merged in 2024-04, with the labels that each got.

#1575 Integrate Loops.so for email marketing
  .env.example
  package.json
  src/lib/game-saving/email.ts
  src/pages/api/auth/email-login-code.ts
  src/pages/api/games/save.ts
  yarn.lock
Labels: enhancement

#1560 Treasure-Hunt-Adventure
  games/Treasure-Hunt-Adventure.js
Labels: submission

#1564 Mind Game
  games/Mind_game.js
  games/img/Mind_game.png
Labels: submission

#1573 orbit blaster pull request
  games/img/orbit_blaster.png
  games/orbit_blaster.js
Labels: submission

#1402 Super_Platformer
  games/Super_Platformer.js
Labels: submission

#1583 Formula_1
  games/Formula_1.js
  games/img/Formula_1.png
Labels: submission

#1582 Jeff Boxos
  games/jeff_boxos.js
Labels: submission

#1581 Cheese-Hunt
  games/Cheese-Hunt.js
Labels: submission

#1570 Add Game Chase Escape
  games/ChaseEscape.js
  games/img/ChaseEscape.png
Labels: submission

#1593 Catch the Egg
  games/Catch_the_Egg.js
  games/img/Catch_the_Egg.png
Labels: submission

#1571 spiano
  games/spiano.js
Labels: submission

#1591 2 Player Maze Runner
  games/2Psplashflame.js
Labels: submission

#1595 My game for the Penny's Big Breakaway Sprig Jam
  games/Penny_s_Quest.js
Labels: submission, penny

#1598 Pennys Big Breakaway Platformer
  games/PennyPlatformer.js
Labels: submission, penny

#1599 Box_Guy
  games/Box_Guy.js
  games/img/Box_Guy.png
Labels: submission

#1613 SprigBattleShip
  games/SprigbattleShip.js
Labels: submission
