Repository hackclub/sprig, pull requests merged in 2024-07, with the labels that each got.

#1844 Add files via upload
  games/stopwatch.js
Labels: submission

#1786 Snake against a friend
  games/img/snake_against_a_friend.png
  games/snake_against_a_friend.js
Labels: submission

#1821 Tech Catcher!
  games/techCatcher.js
Labels: submission

#1847 Add files for Space Adventures
  games/img/space_adventures.png
  games/space_adventures.js
Labels: submission

#1851 Pong
  games/img/pong_irtaza2009.png
  games/pong_irtaza2009.js
Labels: submission

#1855 Fight against COVID
  games/fight_against_covid.js
Labels: submission

#1856 Hey_Hay_Cow
  games/Hey_Hay_Cow.js
Labels: submission

#1857 Get The Green Game
  games/get_the_green.js
  games/img/get_the_green.png
Labels: submission

#1867 Space_Race_v1
  games/Space_Race_v1.js
  games/img/Space_Race_v1.png
Labels: submission

#1874 tanks
  games/tanks.js
Labels: submission

#1876 TicTacToe
  games/TicTacToe.js
  games/img/TicTacToe.png
Labels: submission

#1880 Ping Pong
  games/Ping-Pong.js
  games/img/Ping-Pong.png
Labels: submission

#1891 walk_in_order
  games/img/walk_in_order.png
  games/walk_in_order.js
Labels: submission

#1793 Adding the dodging game
  games/catching_game.js
Labels: submission, initial review performed

#1882 Bomberman
  games/Bomberman.js
  games/img/Bomberman.png
Labels: submission

#1884 Traditional_Snake
  games/Traditional_Snake.js
Labels: submission

#1824 timing
  games/img/timing.png
  games/timing.js
Labels: submission, initial review performed

#1896 8-Sprig
  games/8-Sprig.js
  games/img/8-Sprig.png
Labels: submission

#1886 Blackjack
  games/blackjack.js
  games/img/blackjack.png
Labels: submission

#1864 Pixel_Peril
  games/Pixel_Peril.js
Labels: submission, initial review performed

#1889 Runaway
  games/Runaway.js
Labels: submission

#1906 Jumping banana
  games/jumping_banana.js
Labels: submission

#1903 Update tanks.js
  games/tanks.js
Labels: submission

#1910 added my game: Slap-a-Fish
  games/Slap-A-Fish.js
Labels: submission

#1871 Rescue your chinchilla!
  games/img/rescue_your_chinchilla.png
  games/rescue_your_chinchilla.js
Labels: submission, initial review performed

#1877 sprig_clicker
  games/img/sprig_clicker.png
  games/sprig_clicker.js
Labels: submission, initial review performed

#1895 Path Master
  games/Path_Master.js
Labels: submission

#1899 Boxy
  games/boxy.js
Labels: submission

#1908 Add files via upload
  CheckerInvasion.js
Labels: submission

#1917 Clutter Cleanup
  games/Clutter_Cleanup.js
Labels: submission, initial review performed

#1893 add: hallowed knight
  games/hallowed_knight.js
  games/img/hallowed_knight.png
Labels: submission

#1865 LittleSpringGeme
  games/LittleSpringGame.js
Labels: submission, initial review performed

#1879 Monkey_Demolition
  games/Monkey_Demolition.js
Labels: submission, initial review performed

#1878 Add files via upload
  games/banana_runner.js
Labels: submission, initial review performed

#1885 Half-fry
  games/Half-fry.js
  games/img/Half-fry.png
Labels: submission, initial review performed

#1897 Slimer
  games/Slimer.js
Labels: submission, initial review performed

#1911 Added my space invaders game
  games/Space_Invaders.js
Labels: submission

#1944 Name modal instead of auto generation
  games/getting_started-0.md
  games/sprig_dodge-0.md
  public/login_background.webp
  src/components/big-interactive-pages/editor.tsx
  src/components/design-system/inline-input.tsx
  src/components/navbar-editor.tsx
  src/components/navbar-main.tsx
  src/components/popups-etc/project-name-creation.tsx
  src/components/popups-etc/project-name-creator.module.css
  src/lib/game-saving/account.ts
  src/pages/index.astro
  src/pages/~/index.astro
  src/pages/~/new-game.astro
  src/pages/~/new.ts
Labels: feature request

#1931 brainboom
  games/brainboom.js
  games/img/brainboom.png
Labels: submission

#1933 Sprig Dungeons
  games/SprigDungeons.js
  games/img/SprigDungeons.png
Labels: submission

#1936 Gravity Platformer Game
  games/gravity-platformer.js
Labels: submission

#1942 theLostPenguin
  games/TheLostPenguin.js
Labels: submission

#1962 Galaxy Dodger
  games/Galaxy_Dodger.js
  games/img/Galaxy_Dodger.PNG
Labels: submission

#1963 topdownshooter
  games/img/topdownshooter.png
  games/topdownshooter.js
Labels: submission

#1958 Up, Down, Top-down
  games/Up_Down_Top-down.js
  games/img/Up_Down_Top-down.png
Labels: submission

#1946 Add "Kilroy Saves the Game"
  games/img/kilroy_saves_the_game.png
  games/kilroy_saves_the_game.js
Labels: submission

#1983 Fixed bugs that were in my game. The game is already in the gallery
  games/Space_Invaders.js
Labels: update

#1982 Waze
  games/Waze.js
Labels: submission

#1978 Add files via upload
  games/the-maze.js
Labels: submission

#1973 Tic-Tac-Toe-YZ
  games/Tic-Tac-Toe-YZ.js
  games/img/Tic-Tac-Toe-YZ.png
Labels: submission, initial review performed

#1995 SokobanLike
  games/sokobanlike.js
Labels: submission, initial review performed

#1970 CandyShopper
  games/candyshopper.js
  games/img/candyshopper.png
Labels: submission, initial review performed

#2014 Add DDE
  games/Dance_Dance_Engine!.js
Labels: submission

#1790 Solstice
  games/Solstice_game.js
Labels: submission, initial review performed

#1905 Find a Friend
  games/find_a_friend.js
  games/img/find_a_friend.png
Labels: submission, initial review performed

#1913 TheSpaceGuardian
  games/TheSpaceGuardian.js
  games/img/TheSpaceGuardian.png
Labels: submission, initial review performed

#1924 2P_Fighting_Game
  games/2P_Fighting_Game.js
Labels: submission

#1998 Divine_Tree_Man_Saves_A_Forest
  games/Divine_Tree_Man_Saves_A_Forest.js
Labels: submission

#2001 Rythym_Mania
  games/Rythym_Mania.js
  games/img/Rythym_Mania.png
Labels: submission

#2039 Math Quiz Game
  games/img/math-quiz-game.png
  games/math-quiz-game.js
Labels: submission

#2033 Addded Stickman game
  games/Stickman.js
Labels: submission

#2031 Ducky Maze Game
  games/img/maze game.png
  games/maze game.js
Labels: submission

#1890 Added Dodgy-Day Game
  games/Dodgy-Day.js
Labels: submission

#2030 Flip a Coin
  games/Flip_a_Coin.js
  games/img/Flip_a_Coin.png
Labels: submission

#1957 Add files via upload
  games/amongus.js
Labels: submission, initial review performed

#2027 Knight Buster
  games/knight-buster.js
Labels: submission

#1964 Golf
  games/golf.js
Labels: submission

#2005 Sprigorous Vigor
  games/img/sprigorous-vigor.png
  games/sprigorous-vigor.js
Labels: submission, initial review performed

#1858 Tag
  games/Tag.js
Labels: submission, initial review performed

#2052 MathRacer
  games/MathRacer.js
  games/img/MathRacer.png
Labels: submission

#2023 Prison Break
  games/maze.js
Labels: submission

#2024 Add Sprigenstein3D to gallery
  games/Sprigenstein3D.js
  games/img/Sprigenstein3D.png
Labels: submission

#2006 Crossy Road
  games/Crossy Road.js
Labels: submission, initial review performed

#2047 Maze_Escape_Reach_The_Yellow_Box
  games/Maze_Escape_Reach_The_Yellow_Box.js
Labels: submission

#2051 Sound Memory
  games/Sound_Memory.js
Labels: submission, initial review performed

#2010 The Two Bananas Game
  games/The-Two-Bananas-Game.js
  games/img/The-Two-Bananas-Game.png
Labels: submission

#2016 Juice_Clicker
  games/Juice_Clicker.js
Labels: submission, initial review performed

#1945 BulletRun
  games/BulletRun.js
Labels: submission, initial review performed

#2056 Yet another platformer
  games/yet_another_platfomer.js
Labels: submission

#2046 Maze with coins traps enemies
  games/Maze_with_coins_traps_enemies.js
Labels: submission

#2040 Doomed
  games/Doomed.js
  games/img/Doomed.png
Labels: submission

#2012 Escape Arcade Prison
  games/escape_arcade_prison.js
  games/img/escape_arcade_prison.png
Labels: submission

#2019 SpriMons
  games/SpriMons.js
  games/img/SpriMons.png
Labels: submission, initial review performed

#2041 Add Bullet Heaven
  games/bullet_heaven.js
  games/img/bullet_heaven.png
Labels: submission, initial review performed

#2022 trap_it
  games/trap_it.js
Labels: submission, initial review performed
