Repository hackclub/sprig, pull requests merged in 2024-10, with the labels that each got.

#2393 Sprock Blast
  games/sprock_blast.js
Labels: submission

#2395 Sprig Shooter
  games/Sprig_Shooter.js
  games/img/Sprig_Shooter.png
Labels: submission

#2413 CoinClash
  games/CoinClash.js
Labels: submission

#2407 [Automated] StarFruit
  games/StarFruit.js
  games/img/StarFruit.png
Labels: submission

#2183 2048_Clone
  games/2048_clone.js
Labels: submission, initial review performed

#2185 Classic-Tetris
  games/Classic-Tetris.js
  games/img/Classic-Tetris.png
Labels: submission, initial review performed

#2423 Hangman Explode
  games/Hangman_Explode.js
  games/img/Hangman_Explode.png
Labels: submission

#2444 Games: add Tug-of-War
  games/Tug-of-War.js
Labels: submission

#2459 [Automated] souptikgame
  games/img/souptikgame.png
  games/souptikgame.js
Labels: submission, approved

#2457 Gomoku
  games/gomoku.js
Labels: submission

#2486 3D Demo
  games/3d_demo.js
  games/img/3d_demo.png
Labels: submission

#2464 [Automated] generic_platformer
  games/generic_platformer.js
  games/img/generic_platformer.png
Labels: submission, initial review performed, approved

#2475 [Automated] FireballFlury
  games/FireballFlury.js
  games/img/FireballFlury.png
Labels: submission

#2463 Put a Sprig in your step
  games/Put a _Sprig_ in_your_step.js
Labels: submission

#2462 looparround
  games/looparround.js
Labels: submission

#2508 Apple_Drop
  games/Apple_Drop.js
  games/img/Apple_Drop.png
Labels: submission

#2515 Platformer Update
  games/Platformer.js
Labels: submission
