Repository hackclub/sprig, pull requests merged in 2024-08, with the labels that each got.

#2091 Arcade Runner
  games/Arcade_Runner.js
  games/img/Arcade_Runner.png
Labels: submission

#2029 shortest porky
  games/img/shortest_porky.png
  games/shortest_porky.js
Labels: submission

#2088 Added falldown mini game
  games/falldown.js
Labels: submission

#2071 Add game: Conway's Game of Life
  games/CONWAYs_GAME_OF_LIFE.js
Labels: submission

#2018 Sprig Dash
  games/sprig_dash.js
Labels: submission

#2059 Dragon Duel
  games/Dragon_Duel_v1.js
Labels: submission

#2060 Rock Paper Scissors
  games/Rock Paper Scissor.js
Labels: submission

#1868 Mr Banana
  games/maze_banana.js
Labels: submission, initial review performed

#1921 MazeMission
  games/MazeMission.js
  games/img/MazeMission.png
Labels: submission

#1926 Maze Chase
  games/img/maze_chase.png
  games/maze_chase.js
Labels: submission

#1941 Get-the-car-out
  games/get_the_car_out.js
Labels: submission, initial review performed

#2020 It's Raining Tacos !
  games/itsrainingtacos.js
Labels: submission, initial review performed

#2049 Chrome Dino Game
  games/chrome_dino_game.js
Labels: submission, initial review performed

#2095 Multiplayer maze race
  games/Multiplayer_maze_race.js
  games/img/Multiplayer_maze_race.png
Labels: submission

#2089 DogMaster
  games/DogMaster.js
  games/img/DogMaster.png
Labels: submission

#2073 Ghoul Thrasher
  games/GhoulThrasherFinal.js
  games/img/GhoulThrasherFinal.png
Labels: submission

#2074 Unfinished Game
  games/unfinished_game.js
Labels: submission

#2100 Traffic_Racer
  games/Traffic_Racer.js
  games/img/Traffic_Racer.png
Labels: submission

#2081 A simple mice catcher game
  games/mice_catcher.js
Labels: submission

#2085 Undertale Sprig Edition
  games/img/undertale-sprig-edition.png
  games/undertale-sprig-edition.js
Labels: submission

#2097 Create Pizzeria.js
  games/Pizzeria.js
Labels: submission

#2087 BlockPusher
  games/BlockPusher.js
Labels: submission, initial review performed

#2090 Maze game
  games/Maze.js
Labels: submission, initial review performed

#2064 Added Astroid World
  games/asteroid-world.js
Labels: submission, initial review performed

#2105 Ninja_Run.js
  games/Ninja_Run.js
Labels: submission

#2082 Stupid Maze
  games/Cobble_Maze.js
Labels: submission, initial review performed

#2117 Tower Defense
  games/TowerDefense.js
Labels: submission

#2098 Sprig Invaders
  games/Sprig Invaders.js
Labels: submission

#2101 Mancala
  games/Mancala.js
  games/img/Mancala.png
Labels: submission

#2114 Dark Labyrinth
  games/Black_Labyrinth.js
  games/img/Black_Labyrinth.png
Labels: submission

#2110 3D_Rasterizer
  games/3D_Rasterizer.js
  games/img/3D_Rasterizer.png
Labels: submission

#2113 Add files via upload
  games/love-bug.js
Labels: submission

#2111 blocked
  games/blocked.js
  games/img/blocked.png
Labels: submission

#2164 Add files via upload
  games/the_maze_with_rain.js
Labels: submission, approved

#2158 clicker-kingdom
  games/Clicker Kingdom.js
Labels: submission, approved

#2154 botdotpng
  games/botdotpng.js
  games/img/botdotpng.png
Labels: submission, approved

#2153 Game Submission: 2P Snake
  games/2p-snake.js
  games/img/2p-snake.png
Labels: submission, approved

#2045 Created keyboard for sprig game (& morse...)
  games/img/keyboardForSprig.png
  games/img/morseOnSprig.png
  games/keyboardForSprig.js
  games/morseOnSprig.js
Labels: submission, approved

#2106 added skibidi game 😍
  games/skibidi-toilet-game.js
Labels: submission, approved

#2121 SuperFighters
  games/SuperFighters.js
  games/img/SuperFighters.png
Labels: submission, approved

#2122 Wronglane
  games/WrongLane.js
  games/img/WrongLane.png
Labels: submission, approved

#2135 added PlasticPickup to the games folder
  games/PlasticPickup.js
Labels: submission, approved

#2136 Added Yet Another Rhythm Game
  games/YetAnotherRhythmGame.js
  games/img/YetAnotherRhythmGame
Labels: submission, approved

#2138 once-twice-thrice
  games/once-twice-trice.js
Labels: submission, approved

#2133 Spring
  games/img/spring.png
  games/spring.js
Labels: submission, approved

#2134 Prison Game
  games/Prison Game.js
  games/img/Prison Game.png
Labels: submission, approved

#2127 Spider
  games/Spider.js
  games/img/Spider.png
Labels: submission, approved

#2128 Villager Vikings
  games/Villager_Vikings.js
Labels: submission, approved

#2132 Puppy Café
  games/PuppyCafe.js
  games/img/PuppyCafe.png
Labels: submission, approved

#2123 Adding Galaga
  games/Galaga.js
Labels: submission, approved

#2131 Orb Dungeon
  games/Orb_Dungeon.js
  games/img/Orb_Dungeon.png
Labels: submission, approved

#2149 Add "The Knight" game by CragglesG
  The-Knight.js
Labels: submission, approved

#2145 Collector's Quest
  games/Collectors-Quest.js
Labels: submission, approved

#2146 Maze_escape
  games/Maze_escape.js
Labels: submission, approved

#2142 spriGO
  games/img/spriGO.png
  games/spriGO.js
Labels: submission, approved

#2139 HELP-ME I-CANT-CODE
  games/HELP ME I CANT CODE.js
Labels: submission, approved

#2188 Push and Peril
  games/Push-Peril.js
Labels: submission

#2186 Dropper
  games/dropper.js
  games/img/dropper.png
Labels: submission

#2181 Update Collector's Quest
  games/Collectors-Quest.js
  games/img/Collectors-Quest.png
Labels: update

#2179 I made a game for Sprig
  games/Astroids.js
  games/img/Asteroids.png
Labels: submission

#2178 Tile Platformer
  games/tile_platformer.js
Labels: submission

#2176 Added Guardian
  games/Guardian.js
Labels: submission

#2184 Circuit Breaker
  games/circuit-breaker.js
Labels: submission

#2174 Add files via upload
  games/Memory_Game.js
Labels: submission

#2125 Fix BFA Login Auth
  src/components/big-interactive-pages/login.tsx
  src/components/popups-etc/draft-warning.tsx
  src/lib/game-saving/account.ts
  src/lib/game-saving/auth-helper.ts
  src/pages/api/auth/submit-code.ts
Labels: bug, high priority

#2169 Monkey quest 3: lightless knights
  games/Monkey quest 3 lightless knights.js
Labels: submission

#2168 Food_Stealer
  games/Food Stealer.js
Labels: submission

#2195 Easy Peasy
  games/EasyPeasy.js
  games/img/EasyPeasy.png
Labels: submission

#2197 Sewer_Flood
  games/Sewer_Flood.js
  games/img/Sewer_Flood.png
Labels: submission

#2211 Score_it
  games/Score_it.js
  games/img/Score_It.PNG
Labels: submission

#2198 Update Easy Peasy
  games/EasyPeasy.js
Labels: submission, approved

#2199 spropper
  games/img/spropper.png
  games/spropper.js
Labels: submission, approved

#2202 added my game color dino
  games/color dino.js
Labels: submission, approved

#2208 oneWay
  games/oneWay.js
Labels: submission, approved

#2210 Hole In The Wall
  games/Hole_In_the_Wall.js
Labels: submission, approved

#2212 Add files via upload
  games/Humpty Runner.js
Labels: submission, approved

#2213 Add files via upload
  games/Apples-and-Oranges.js
Labels: submission, approved

#2137 Simon-Sees
  games/Simon-Sees.js
Labels: submission, approved

#2167 Camion_en_Mexico
  games/Camion_en _Mexico.js
Labels: submission, approved

#2173 Cops and Criminals
  games/cops_and_criminals.js
  games/img/cops_and_criminals.png
Labels: submission, initial review performed

#2226 Updating Sewer_Flood
  games/Sewer_Flood.js
Labels: submission

#2222 SuperFighters Game Bug Fix & New Features!
  games/SuperFighters.js
Labels: submission

#2240 Cat_Cafe
  games/Cat_Cafe.js
  games/img/Cat Cafe.png
Labels: submission, approved

#2242 Dungeon_Master
  games/Dungeon_Master.js
  games/img/Dungeon_Master.png
Labels: submission, approved

#2233 Photosynthesis
  games/photosynthesis.js
  shapely_electabuzz (1).js
Labels: submission, approved

#2236 Least_Tiles
  games/Least_Tiles.js
Labels: submission, approved

#2237 9 tiles
  games/9 tiles.js
Labels: submission, approved

#2223 Uploading "Brick Blaster" Game
  games/brick_blaster.js
Labels: submission, approved

#2225 Flying Fish Platformer Game
  games/Flying_Fish_Platformer_Game.js
  games/img/Flying_Fish_Platformer_Game.png
Labels: submission, approved

#2232 Enigma
  games/enigma.js
Labels: submission, approved

#2217 Ghoul Thrasher(Bugfix and Balance changes)
  games/GhoulThrasherFinal.js
Labels: submission

#2216 trap runner
  games/trap hunt.js
Labels: submission, approved

#2220 The Sequence
  games/The Sequence v1.js
  games/img/the_sequence.png
Labels: submission, approved
