Repository hackclub/sprig, pull requests merged in 2024-11, with the labels that each got.

#2530 (🐍 Sprigin_Snakey.js 🐍) Add files via upload
  games/Sprigin_Snakey.js
Labels: submission, initial review performed

#2529 Add Monster Mayhem
  games/MonsterMayhem.js
Labels: submission

#2533 Create Streetblink.js
  games/Streetblink.js
Labels: submission

#2547 Finish Monster Mayhem
  games/MonsterMayhem.js
  games/img/MonsterMayhem.png
Labels: submission

#2553 [Sprig App] Zoom
  games/Zoom.js
  games/img/Zoom.png
Labels: submission

#2550 Add files via upload
  games/Dangerous-Pac.js
Labels: submission

#2548 Infinity Jump Lite
  games/Infinity-Jump-Lite.js
  games/img/Infinity-Jump-Lite.png
Labels: submission

#2574 [Sprig App] Save The Seas
  games/Save-The-Seas.js
Labels: submission

#2593 Add files via upload
  games/ShapeQuest.js
Labels: submission

#2546 DonkeyKong
  games/DonkeyKong.js
  games/img/DonkeyKong.png
Labels: submission, initial review performed

#2597 [Sprig App] Pixeltron 6000
  games/Pixeltron-6000.js
  games/img/Pixeltron-6000.png
Labels: submission

#2542 FlyMyKite
  games/FlyMyKite.js
Labels: submission, initial review performed

#2615 [Sprig App] Cash Clicker!
  games/Cash-Clicker!.js
Labels: submission, approved

#2616 [Sprig App] Set
  games/Set.js
Labels: submission

#2612 [Sprig App] Maze Madness (RAGE GAME)
  games/Maze-Madness-(RAGE-GAME).js
Labels: submission, approved

#2645 [Sprig App] The Warriors Quest v3
  games/Warriors_quest.js
Labels: submission

#2624 Find Tommy
  games/Find-Tommy.js
Labels: submission, initial review performed, approved

#2626 [Sprig App] Crystal Caper: The Jewel Thieves
  games/Crystal-Caper:-The-Jewel-Thieves.js
Labels: submission, initial review performed, approved

#2634 Travelling Courier
  games/Travelling_Courier.js
Labels: submission, approved

#2637 [Sprig App] PuzzleRun
  games/PuzzleRun.js
  games/img/PuzzleRun.png
Labels: submission

#2642 [Sprig App] Infinite Platformer
  games/Infinite-Platformer.js
  games/img/Infinite-Platformer.png
Labels: submission

#2641 [Sprig App] Advanced Clicking Simulator
  games/Advanced-Clicking-Simulator.js
  games/img/Advanced-Clicking-Simulator.png
Labels: submission

#2647 [Sprig App] dot10
  games/dot10.js
Labels: submission
