Repository hackclub/sprig, pull requests merged in 2025-10, with the labels that each got.

#3274 [Sprig App] Dex
  games/Dex.js
  games/img/Dex.png
Labels: triaged, awaiting-review

#3273 Trickster Trials
  games/img/trickster_trials.png
  games/trickster_trials.js
Labels: triaged, awaiting-review

#3285 Football Adventure
  games/Football Adventure (1).js
Labels: triaged, awaiting-review

#3315 Pickle-Run
  games/Pickle-Run.js
Labels: triaged, awaiting-review

#3322 Arrow
  games/Arrow.js
  games/img/Arrow.png
Labels: triaged, awaiting-review

#3323 [Sprig App] Block Dash
  games/Block-Dash.js
Labels: triaged, awaiting-review

#3338 [Sprig App] Space Invader
  games/Space-Invader.js
  games/img/Space-Invader.png
Labels: triaged, awaiting-review

#3333 [Sprig App] Dungen
  games/Dungen.js
  games/img/Dungen.png
Labels: triaged, awaiting-review

#3325 Plant survivor
  games/Plant-survivor.js
Labels: triaged, awaiting-review

#3317 Retrofarmin Simulator
  games/Retrofarmin_simulator.js
  games/img/Retrofarmin_simulator.png
Labels: triaged

#3171 Tris.js
  games/Tris.js
  games/img/Tris.png
Labels: initial review performed, triaged, awaiting-review

#3308 wall_defense
  games/img/wall_defense.png
  games/wall_defense.js
Labels: triaged, awaiting-review

#3309 [Sprig App] PatternPusher
  games/PatternPusher.js
Labels: triaged, awaiting-review

#3348 Platformation.js
  games/Platformation.js
Labels: triaged, awaiting-review

#3346 Stack
  games/Stack.js
  games/img/Stack.PNG
Labels: triaged, awaiting-review
