Repository hackclub/sprig, pull requests merged in 2025-02, with the labels that each got.

#2836 [Sprig App] Legally Distinct Yellow Creature Collects Bananas
  games/Legally-Distinct-Yellow-Creature-Collects-Bananas.js
Labels: submission, initial review performed, approved

#2814 SkyFall
  games/SkyFall.js
Labels: submission, initial review performed

#2816 [Sprig App] nolimits
  games/nolimits.js
Labels: submission, initial review performed

#2830 Casino - Don't Gamble
  games/Casino_-_Dont_Gamble.js
  games/img/Casino_-_Dont_Gamble.png
Labels: submission, initial review performed, approved

#2831 Pull Request for Lunk
  games/Lunk.js
Labels: submission, initial review performed

#2847 Sprig App - Subconscious Revolution
  games/Subconscious-Revolution.js
  games/img/Subconscious-Revolution.png
Labels: submission
